### ISSUE TITLE
construct_im doesn't properly work with int_vector (when constructing a wt_rlmn)

### ISSUE THREAD

**Issue by jendas1** [xxsds/sdsl-lite#71]
Hi,

I am reposting the same problem with more insights and slightly different results as I wrote in the legacy sdsl-lite repo (https://github.com/simongog/sdsl-lite/issues/422).

I came across a strange behaviour of `construct_im` if constructing a wavelet tree (`wt_rlmn`) from an `int_vector` which is depicted in the code below.
In case of loading from int_vector with a compiled time width of 8 `int_vector_compile_time_width_8`, everything works as expected.

But in case of the width set to 5, (int_vector_compile_time_width_5) construct_im doesn't correctly identify the width & displays a warning "Width of int_vector<8> was specified as 5".
Additionally, probably a related error occurs when setting the width by calling `width(8)`.  Now the `construct_im` doesn't display a warning, but also the representation stays as with `int_vector_auto_width`.

It would be great if someone can look into what could be the issue in the sdsl library.

Cheers,
Jan

```c++
#include <iostream>
#include <sdsl/int_vector.hpp>
#include <sdsl/wt_rlmn.hpp>
#include <sdsl/construct.hpp>

using namespace std;
using namespace sdsl;

void int_vector_compile_time_width_8() {
    sdsl::int_vector<8> test = {1,2,3,4,5,6,7,8};
    wt_rlmn<> wt;
    construct_im(wt,test,0);
    for(auto e : wt) {
        cout << int(e) << " ";
    }
    cout << endl;
}

void int_vector_compile_time_width_5() {
    sdsl::int_vector<5> test = {1,2,3,4,5,6,7,8};
    wt_rlmn<> wt;
    construct_im(wt,test,0);
    for(auto e : wt) {
        cout << int(e) << " ";
    }
    cout << endl;
}

void int_vector_auto_width() {
    sdsl::int_vector<> test = {1,2,3,4,5,6,7,8};
    wt_rlmn<> wt;
    construct_im(wt,test,0);
    for(auto e : wt) {
        cout << int(e) << " ";
    }
    cout << endl;
}

void int_vector_adj_width() {
    sdsl::int_vector<> test = {1,2,3,4,5,6,7,8};
    test.width(8);
    wt_rlmn<> wt;
    construct_im(wt,test,0);
    for(auto e : wt) {
        cout << int(e) << " ";
    }
    cout << endl;
}

int main(int argc,char** argv) {
    int_vector_compile_time_width_8(); // 1 2 3 4 5 6 7 8

    int_vector_compile_time_width_5(); // Warning: Width of int_vector<8> was specified as 5
                                       // Length is 40 bits
                                       // 65 12 82 204 65

    int_vector_auto_width(); // Warning: Width of int_vector<8> was specified as 64
                             // Length is 512 bits
                             // 1 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 5 0 0 0 0 0 0 0 6 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 8 0 0 0 0 0 0

    int_vector_adj_width(); // 1 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 5 0 0 0 0 0 0 0 6 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 8 0 0 0 0 0 0
    return 0;
}
```

**Comment by rrahn** [comment]
@jendas1 Not sure if I can really help you out here, as I am just starting to look into the implementations. But is `sdsl::int_vector<5>` even a valid use case? According to the cheat sheet values can be 0, 1, 8, 16, 32 and 64. For the `auto_width` implementation I am not entirely sure what happens. But it seems that the dynamic int vector does not work well with the initialiser list constructor, since no proper width was set before assigning the values. But I didn't debug it just looked into the code, so I might be entirely wrong here. Anyway, you could check if in your example of `int_vector_auto_width` if `test` actually has the proper size and values after constructing it. As a fix I would also recommend using the specific constructor setting the width at construction time:

From the cheat sheet
> int_vector<>(n,x,l), with n equals size, x default integer value, l width of integer (has no effect for w >0)

Again, I am absolutely no expert on the internals of the SDSL, but maybe you give it a try.

**Comment by eseiler** [comment]
#84 should resolve this.
The problem is that we read the header of the `int_vector`, which contains the width among other things.
For some reason, we call the `read_header` of an `int_vector` with a fixed width instead of one with a width of `0`. That's why we get a warning. 
We do not know the width of the vector, that's the reason we call `read_header` to begin with; so we also shouldn't set some arbitrary width.
